[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Dive into <a class="text-muted" href="https://actocracy.xyz/" target="_blank">Actocracy App</a>'
    #alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[cn]
  languageName = "中文"
  contentDir = "content/cn"
  weight = 15
  [cn.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
    #footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    #alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'

[es]
  languageName = "Español"
  contentDir = "content/es"
  weight = 20
  [es.params]
    languageISO = "ES"
    languageTag = "es-BR"
    #footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    #alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'

[ru]
  languageName = "Русский"
  contentDir = "content/ru"
  weight = 25
  [ru.params]
    languageISO = "RU"
    languageTag = "ru-RU"
    description = "Источник знаний по Актократии"
    #titleAddition = "Modern documentatie-thema"
    #description = "Doks is een Hugo-thema waarmee je moderne documentatie-websites kunt bouwen die veilig, snel en klaar voor SEO zijn — standaard."
    #titleHome = "Doks thema"
    #footer = 'Mogelijk gemaakt door <a href="https://www.netlify.com/">Netlify</a>, <a href="https://gohugo.io/">Hugo</a>, en <a href="https://getdoks.org/">Doks</a>'
    #alertText = 'Introductie van het Doks-kinderthema, verschillende DX + UX-updates en meer! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.2/">Bekijk Doks v0.2</a>'

[ar]
  languageName = "اَلْعَرَبِيَّة"
  contentDir = "content/ar"
  weight = 30
  [ar.params]
    languageISO = "AR"
    languageTag = "ar-SA"
    #footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    #alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'

[in]
  languageName = "हिंदी"
  contentDir = "content/in"
  weight = 40
  [in.params]
    languageISO = "IN"
    languageTag = "hi-IN"
    #footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    #alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'

[tr]
  languageName = "Türkçe"
  contentDir = "content/tr"
  weight = 35
  [tr.params]
    languageISO = "TR"
    languageTag = "tr-TR"
    #footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    #alertText = 'Neue Version ist da! <a class="alert-link stretched-link" href="https://getdoks.org/blog/doks-v0.5/">Doks v0.5</a>'