[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Dive into <a class="text-muted" href="https://actocracy.xyz/" target="_blank">Actocracy Ecosystem</a>'

[cn]
  languageName = "中文"
  contentDir = "content/cn"
  weight = 15
  [cn.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
    #footer = 'Gebaut mit <a class="text-muted" href="https://gethyas.com/">Hyas</a>'

[es]
  languageName = "Español"
  contentDir = "content/es"
  weight = 20
  [es.params]
    languageISO = "ES"
    languageTag = "es-BR"
    footer = 'Mergulhe no <a class="text-muted" href="https://actocracy.xyz/" target="_blank">Ecossistema Actocracy</a>'

[ru]
  languageName = "Русский"
  contentDir = "content/ru"
  weight = 25
  [ru.params]
    languageISO = "RU"
    languageTag = "ru-RU"
    description = "Источник знаний по Актократии"

[ar]
  languageName = "اَلْعَرَبِيَّة"
  contentDir = "content/ar"
  weight = 30
  [ar.params]
    languageISO = "AR"
    languageTag = "ar-SA"
    footer = 'انغمس في <a class="text-muted" href="https://actocracy.xyz/" target="_blank">نظام Actocracy البيئي</a>'

[tr]
  languageName = "Türkçe"
  contentDir = "content/tr"
  weight = 35
  [tr.params]
    languageISO = "TR"
    languageTag = "tr-TR"
    footer = '<a class="text-muted" href="https://actocracy.xyz/" target="_blank">Actocracy Ekosistemine</a> Dalın'

[in]
  languageName = "हिंदी"
  contentDir = "content/in"
  weight = 40
  [in.params]
    languageISO = "IN"
    languageTag = "hi-IN"
    footer = '<a class="text-muted" href="https://actocracy.xyz/" target="_blank">Actocracy पारिस्थितिकी तंत्र</a> में गोता लगाएँ'